#!/usr/bin/env bash
# shellcheck disable=SC2086
# display information about subdomains

# Function to get DNS record information
get_record_info() {
    local domain=$1
    local subdomain=$2

    # Perform a DNS lookup using dig and format the output with awk
    dig_result=$(dig +noall +answer $subdomain.$domain A)
    
    if [ -z "$dig_result" ]; then
        echo "The subdomain $subdomain does not exist."
    else
        record_type=$(echo "$dig_result" | awk '{print $4}')
        destination=$(echo "$dig_result" | awk '{print $5}')
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    fi
}

# Main script logic
main() {
    local domain=$1
    local subdomain=$2

    if [ -z "$domain" ]; then
        echo "Domain is mandatory."
        exit 1
    fi

    if [ -z "$subdomain" ]; then
        # Default subdomains
        subdomains=("www" "lb-01" "web-01" "web-02")
        for sub in "${subdomains[@]}"; do
            get_record_info $domain $sub
        done
    else
        get_record_info $domain $subdomain
    fi
}

# Ignore shellcheck case SC2086
# Call the main function with provided arguments
main "$@"
