#!/usr/bin/env bash
#Transfers a file from our client to a server
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
SSH_KEY=$4
if [[ $# -ge 3 ]];
then
	if [[ $# -eq 3 ]];
	then
		scp -o StrictHostKeyChecking=no "${PATH_TO_FILE}" "${USERNAME}"@"${IP}":~/
	else
		scp -o StrictHostKeyChecking=no -i "${SSH_KEY}" "${PATH_TO_FILE}" "${USERNAME}"@"${IP}":~/
	fi
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
