#!/usr/bin/env bash
#install and configure Nginx web-server
echo "Hello World!" | sudo tee /var/www/html/index.html
# Ensure Nginx is listening on port 80 (default configuration)
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

