#!/usr/bin/env bash
# Update package lists
sudo apt-get update
# Install Nginx
sudo apt-get install -y nginx
# Create the custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
# Create a new Nginx server block configuration
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOL
server {
    listen 80;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }

    location /redirect_me {
        return 301 http://youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOL

# Check Nginx configuration for syntax errors
sudo nginx -t

# If the configuration is correct, reload Nginx to apply changes
if [ $? -eq 0 ]; then
    sudo nginx -s reload
else
    echo "Nginx configuration test failed. Exiting."
    exit 1
fi

# Ensure the firewall allows traffic on port 80
sudo ufw allow 'Nginx HTTP'

# Verify Nginx is running
sudo service nginx status

# Verify Nginx is serving the custom 404 page
curl -I http://localhost/nonexistent

