#!/usr/bin/env bash
#Install and configure the nginx webserver with redirections and  a costumized notfound page
apt-get -y install nginx

service nginx start

ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# Ensure Nginx is listening on port 80 (default configuration)
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

#Give the user  ownership to website files
chown -R $"USER":$"USER" /var/www/html
chmod -R 755 /var/www

# Redirect to /redirect_me to a youtube video
sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Setup 404 page
printf "Ceci n'est pas une page\n" >> /var/www/html/error_404.html
sed -i '38i\error_page 404 /error_404.html;' /etc/nginx/sites-available/default

service nginx restart

