#!/usr/bin/env bash
# Update and upgrade the system
apt update
apt upgrade -y

# Install HAProxy
apt-get install -y haproxy

# Configure HAProxy
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend bouz.tech
    bind 0:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 518901-web-01 54.198.53.210:80 check
    server 518901-web-02 52.23.212.104:80 check
EOF

# Enable HAProxy to start on boot
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy service to apply changes
service haproxy restart
