#!/usr/bin/env bash
# tell a story

IFS=:

while read -r line; do
	read -ra l <<< "$line"
	echo "The user ${l[0]} is part of the ${l[3]} gang, lives in ${l[5]} and rides ${l[6]}. ${l[2]}'s place is protected by the passcode ${l[1]}, more info about the user here: ${l[4]}"
done </etc/passwd
