#!/usr/bin/env bash
# Bad luck from different countries
x=1
while [ $x -le 20 ]
do
	echo $x
	case $x in

	4)
		echo "bad luck from China"
	;;
	9)
		echo "bad luck from Japan"
	;;
	17)
		echo "bad luck from Italy"
	;;
	esac
	((x++))
done
