#!/usr/bin/env bash
#This script sets up the firewall
#Update the apt manager
sudo apt update -y
#Installing ufw
sudo apt install ufw -y
#Setting up Default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing
#Allowing SSH Connections
sudo ufw allow OpenSSH
sudo ufw allow 22
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable -y
